package com.mycompany.mindmap.Telas.Tarefa;

import com.mycompany.mindmap.Telas.Inicio.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class OpcoesTarefas extends javax.swing.JPanel {

    /**
     * Creates new form OpcoesAbas
     */
    public OpcoesTarefas() {
        initComponents();        
    }
    
    public void initEvent(TableActionEventTarefa evento, int linha){
        opcaoEditar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                evento.editarTarefa(linha);
            }
        });
        opcaoExcluir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                evento.excluirTarefa(linha);
            }
        });
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcaoEditar = new com.mycompany.mindmap.Telas.Inicio.ActionButton();
        opcaoExcluir = new com.mycompany.mindmap.Telas.Inicio.ActionButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 51, 51));

        opcaoEditar.setText("Editar");
        opcaoEditar.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N

        opcaoExcluir.setText("Excluir");
        opcaoExcluir.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        opcaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opcaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opcaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opcaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(opcaoExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void opcaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.mindmap.Telas.Inicio.ActionButton opcaoEditar;
    private com.mycompany.mindmap.Telas.Inicio.ActionButton opcaoExcluir;
    // End of variables declaration//GEN-END:variables
}
