package com.mycompany.mindmap.Telas.Administrador.GastosAdm.Dialogs;

import com.mycompany.mindmap.Telas.Administrador.InicioAdm.*;
import com.mycompany.mindmap.Telas.Inicio.*;
import com.mycompany.mindmap.Classes.Aba;
import com.mycompany.mindmap.Classes.ConexaoBD;
import com.mycompany.mindmap.Classes.Gastos;
import com.mycompany.mindmap.Classes.Usuario;
import com.mycompany.mindmap.Classes.dao.AbaDAO;
import com.mycompany.mindmap.Classes.dao.GastosDAO;
import com.mycompany.mindmap.Classes.dao.UsuarioDAO;
import com.mycompany.mindmap.Telas.Administrador.GastosAdm.TelaGastosAdm;
import com.mycompany.mindmap.Telas.Administrador.TarefasAdm.TelaListarTarefasAdm;
import com.mycompany.mindmap.Telas.Tarefa.TelaListarTarefas;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class DialogSelecionarGastosUsuario extends javax.swing.JDialog {

    /**
     * Creates new form DialogTarefas
     */
    int idUsuarioLogado = 0;
    int idGasto = 0;

    private List<Gastos> pegarGastosDoBanco(int idUsuarioLogado) {
        List<Gastos> gastos = new ArrayList<>();

        String sql = "SELECT * FROM gastos";

        try {
            Connection conn = ConexaoBD.obtemConexao();
            PreparedStatement consulta = conn.prepareStatement(sql);
            ResultSet rs = consulta.executeQuery();

            while (rs.next()) {
                int idGastos = rs.getInt("idGastos");
                Double saldo = rs.getDouble("saldo");
                Double despesas = rs.getDouble("despesas");
                int idUsuario = rs.getInt("idUsuario");
                gastos.add(new Gastos(idGastos, saldo, despesas, idUsuario));
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        return gastos;
    }

    public DialogSelecionarGastosUsuario(java.awt.Frame parent, boolean modal, int idUsuario) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        idUsuarioLogado = idUsuario;

        try {
            List<Gastos> gastos = pegarGastosDoBanco(idUsuarioLogado);
            for (Gastos gasto : gastos) {
//                int a = gasto.getIdGastos();
//                String b = a.

                UsuarioDAO usuarioDao = new UsuarioDAO();
                Usuario usuario = usuarioDao.selecionarPorId(gasto.getIdUsuario());
//                comboBoxAbas.addItem(String.valueOf(gasto.getIdUsuario()));
                comboBoxUsuario.addItem(usuario.getNome());

                comboBoxUsuario.addActionListener(e -> {

                    int indexSelecionado = comboBoxUsuario.getSelectedIndex();
                    if (indexSelecionado >= 0) {
                        Gastos gastoSelecionado = gastos.get(indexSelecionado);                        
                        txtIdGasto.setText(String.valueOf(gastoSelecionado.getIdGastos()));
                    }

                });
            }            
//            System.out.println(idUsuarioLogado);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxUsuario = new javax.swing.JComboBox<>();
        buttonSelecionar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        txtIdGasto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("Você deseja visualizar gastos de qual usuário?");

        comboBoxUsuario.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        buttonSelecionar.setBackground(new java.awt.Color(0, 194, 255));
        buttonSelecionar.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        buttonSelecionar.setForeground(new java.awt.Color(255, 255, 255));
        buttonSelecionar.setText("SELECIONAR");
        buttonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelecionarActionPerformed(evt);
            }
        });

        buttonVoltar.setBackground(new java.awt.Color(255, 41, 69));
        buttonVoltar.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        buttonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        buttonVoltar.setText("VOLTAR");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        txtIdGasto.setEditable(false);
        txtIdGasto.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        txtIdGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdGastoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setText("Id de gasto");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setText("Usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(buttonSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        this.dispose();
        UsuarioDAO usuarioDao = new UsuarioDAO();
        Usuario usuario = usuarioDao.selecionarPorId(idUsuarioLogado);
        TelaInicioAdm telainicio = new TelaInicioAdm(usuario);
        telainicio.setVisible(true);
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelecionarActionPerformed
//        comboBoxAbas.getSelectedIndex();
//        System.out.println("Aba selecionada: " + comboBoxAbas.getSelectedItem() + " " + idAba);
//        txtIdAba.setText
//          JOptionPane.showMessageDialog(null, "Id da aba selecionada: " + txtIdAba.getText());
        UsuarioDAO usuarioDao = new UsuarioDAO();
        Usuario usuario = usuarioDao.selecionarPorId(idUsuarioLogado);
        
        idGasto = Integer.parseInt(txtIdGasto.getText());
        
        
//        AbaDAO abaDao = new AbaDAO();
//        Aba aba = abaDao.selecionarAbaPorId(idGasto);
        GastosDAO gastoDao = new GastosDAO();
        Gastos gasto = gastoDao.selecionarGastosPorIdGastos(idGasto);
        
        TelaGastosAdm telaGastos = new TelaGastosAdm(usuario, gasto);
        telaGastos.setVisible(true);
//        JOptionPane.showMessageDialog(null, "Selecionado: " + idGasto);
        
        this.dispose();
        
    }//GEN-LAST:event_buttonSelecionarActionPerformed

    private void txtIdGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdGastoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogSelecionarGastosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogSelecionarGastosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogSelecionarGastosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogSelecionarGastosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                Usuario usuario = null;
                DialogSelecionarGastosUsuario dialog = new DialogSelecionarGastosUsuario(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSelecionar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JComboBox<String> comboBoxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtIdGasto;
    // End of variables declaration//GEN-END:variables
}
